### ISSUE TITLE
how to save the model ?

### ISSUE THREAD

**Issue by Tlntin** [lorey/mlscraper#26]
I want to save model, so i can use it for next time.
I can't found  how to do it in example

**Comment by Tlntin** [comment]
i try to use pickle to save scrapper, it work well.

**Comment by lorey** [comment]
Hi @Tlntin, thanks for getting in touch and even posting the answer you found. Would also be my solution of choice for now. Time for me to create some kind of documentation, I guess...

**Comment by entrptaher** [comment]
Sample code for future reference,

```py
# train the model
scraper = train_scraper(training_set)

# save the file for future use
file = open('model.pickle', 'wb')
pickle.dump(scraper, file)
file.close()

# load it later
file = open('model.pickle', 'rb')
scraper = pickle.load(file)
file.close()
```
