### ISSUE TITLE
Does not work with some sites

### ISSUE THREAD

**Issue by GyurkanM** [lorey/mlscraper#35]
Does not return results for sites like bbc.com, dnevnik.bg etc when I to scrape even the titles only from the articles.

**Comment by lorey** [comment]
Sorry, I cannot possibly guess the issue without more information from your side.

**Comment by GyurkanM** [comment]
@lorey https://gist.github.com/GyurkanM/c48872e2ff024fdea7b4e9e23b27c7e9

**Comment by lorey** [comment]
Try adding more examples.

**Comment by GyurkanM** [comment]
also another example where title can be scraped but when I try scraping author it is unsuccessful - https://gist.github.com/GyurkanM/e19493f854d1263f93b970df85dd6cae

**Comment by lorey** [comment]
You're doing zero work on your side, I can not and will not help you further. I'm a human being doing this for free, not ChatGPT.

**Comment by GyurkanM** [comment]
What does it mean zero work, I have just tried your project and try to use it according to the documentation and give feedback to you whats my experience, I did not request help, just pointed out cases where the script does not work....
