### ISSUE TITLE
训练出现错误

### ISSUE THREAD

**Issue by liliwen365** [lorey/mlscraper#36]
网页中有这个5190，是不是因为网页提供的数据存在空格或空行？这种情况如何解决，能不能忽略空行只提取数据？
我的代码：
einstein_url = 'http://www.i001.com/main1.shtml'
resp = requests.get(einstein_url)
assert resp.status_code == 200
training_set = TrainingSet()
page = Page(resp.content)
sample = Sample(page, {'name': '5190'})
training_set.add_sample(sample)
scraper = train_scraper(training_set)

反馈错误：
ValueError: <td align="middle" bgcolor="#ffffff" width="68">
                                        
                                        5190
                                    </td> is not in list

**Comment by lorey** [comment]
Meine Muttersprache ist Deutsch. Sollen wir uns in der Mitte treffen und Englisch sprechen?
