### ISSUE TITLE
Module not found error?

### ISSUE THREAD

**Issue by Immortalus13** [lorey/mlscraper#43]
Does mlscraper still work? I cannot get it to run (not even the sample code). I always get a ModuleNotFoundError:

> ModuleNotFoundError: No module named 'mlscraper.html

```
import requests
from mlscraper.html import Page
from mlscraper.samples import Sample, TrainingSet
from mlscraper.training import train_scraper

# fetch the page to train
einstein_url = 'http://quotes.toscrape.com/author/Albert-Einstein/'
resp = requests.get(einstein_url)
assert resp.status_code == 200

# create a sample for Albert Einstein
# please add at least two samples in practice to get meaningful rules!
training_set = TrainingSet()
page = Page(resp.content)
sample = Sample(page, {'name': 'Albert Einstein', 'born': 'March 14, 1879'})
training_set.add_sample(sample)

# train the scraper with the created training set
scraper = train_scraper(training_set)

# scrape another page
resp = requests.get('http://quotes.toscrape.com/author/J-K-Rowling')
result = scraper.get(Page(resp.content))
print(result)
# returns {'name': 'J.K. Rowling', 'born': 'July 31, 1965'}
```

The package is definitely installed, though:
<img width="678" alt="image" src="https://github.com/lorey/mlscraper/assets/157795088/1c194e5a-9a8a-432d-a2f9-c14d568499a3">

Or what am I missing

**Comment by lorey** [comment]
Please check the installed version and see https://github.com/lorey/mlscraper#getting-started
You’ve most likely not installed the needed version (1.0+).

**Comment by Immortalus13** [comment]
Thanks, that actually did the trick! Appreciate the quick help!!
